### PR TITLE
Fixed dkim record not showing

### PR DESCRIPTION
**Pull request by hanzala123**
The dkim record was not showing in the output. I have fixed it. It was an issue with the function that gets the TXT records. I replaced it net.LookupTXT along with some other changes.

Context:
I am a Python developer. I had never used go before. Only had used pre-compiled binaries like amass, nuclei etc. I was searching for a tool that would get email related DNS settings and found this amazing tool. But it was not working properly with dkim. I re-created the tool in python for my use. Just for fun I wanted to see if I could fix it. After adding some fmt.Print statements (Never knew you had to import a library for a simple print function :P), I found out that the function that was responsible for fetching TXT records was not working properly when it came to dkim. I read on the internet about the function net.LookupTXT.  I replaced the previous function with this one and the program started working. I also had to make some changes in line 140-150. But now it is working. I have no idea about go best practices and guidelines so please excuse those. This is an amazing tool and I wanted to contribute whatever I can.

Regards,
Hanzala Ibn Zahid

### CODE REVIEW

**Comment by wolveix** [comment]
Hey @hanzala123, thanks for taking the time to open this PR :) 

I'm unaware of any issues with DKIM lookups, and cannot reproduce what you're experiencing. Would you mind providing some additional context or steps to reproduce? Unfortunately, your changes cause the TXT lookups to not conform to the timeouts or any other configurations specified. Perhaps if you could provide the information requested above, we can work together to resolve the issue you're experiencing? :)

**Comment by wolveix** [comment]
@hanzala123 could you show me the command you were using, and the domain you were using it against? This is what I see:

```
❯ ./bin/dss scan globalcyberalliance.org  
domain: globalcyberalliance.org
bimi: v=BIMI1;l=https://bimi.entrust.net/globalcyberalliance.org/logo.svg;a=https://bimi.entrust.net/globalcyberalliance.org/certchain.pem
dmarc: v=DMARC1; p=reject; fo=1; rua=mailto:3941b663@inbox.ondmarc.com,mailto:2zw1qguv@ag.dmarcian.com,mailto:dmarc_agg@vali.email; ruf=mailto:2zw1qguv@fr.dmarcian.com,mailto:gca-ny-sc@globalcyberalliance.org;
dkim: v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB;
spf: v=spf1 include:_u.globalcyberalliance.org._spf.smart.ondmarc.com -all
mx:
    - alt3.aspmx.l.google.com.
    - aspmx.l.google.com.
    - alt2.aspmx.l.google.com.
    - alt4.aspmx.l.google.com.
    - alt1.aspmx.l.google.com.
duration: 265.513458ms
```

**Comment by hanzala123** [comment]
`./dss-linux-amd64 scan reconfirm.nl -a -r mx --checkTls`

This is the one I am using

**Comment by hanzala123** [comment]
`scanResult:
    domain: reconfirm.nl
    mx:
        - reconfirm-nl.mail.protection.outlook.com.
    duration: 628.934068ms
advice:
    bimi:
        - We couldn't detect any active BIMI record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
    dkim:
        - We couldn't detect any active DKIM record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
    dmarc:
        - You do not have DMARC setup! Please visit https://dmarcguide.globalcyberalliance.org to set it up.
    domain:
        - Your domain is using TLS 1.3, no further action needed!
    mx:
        - You have a single mail server setup, but it's recommended that you have at least two setup in case the first one fails.
        - 'reconfirm-nl.mail.protection.outlook.com: Your domain is using TLS version 1.2, and should be upgraded to TLS 1.3.'
    spf:
        - We couldn't detect any active SPF record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this.
`
This is the output I get

**Comment by hanzala123** [comment]
It is selector1 and selector2. They are present in the code.

**Comment by wolveix** [comment]
It looks like your raw DNS record looks like this:

```
selector1._domainkey.reconfirm.nl.      300     IN      TXT     selector1-reconfirm-nl._domainkey.ReConfirmSecurity.onmicrosoft.com.
```

That would explain why it isn't working. I'll implement a recursive search to resolve this :) Thanks for bringing it to our attention!

**Comment by wolveix** [comment]
This has been addressed in the new version. Prebuilt releases will be available shortly :) Thanks again!

**Pull request closed without merging**
